PimTeste/Models/FolhaDePagamento.cs
namespace PimTeste.Models
{
    public class FolhaDePagamento
    {

        public int Id { get; set; }
        public int FuncionarioId { get; set; }

        public Funcionario Funcionario { get; set; }
        public double Valor { get; set; }
        public DateTime DataValor { get; set; }

         //+ prioridades 

    }
}

PimTeste/Models/Funcionario.cs
using Microsoft.AspNetCore.Identity;

namespace PimTeste.Models
{
    public class Funcionario
    {

        public string? NomeFuncionario { get; set; } 

        public string? CPF { get; set; }
        public int LoginId { get; set; }

        public UsuarioLogin? usuario;
        public string? Cargo { get; set; }

        public double Salario { get; set; }
        public string? NomeDepartamento { get; set; }


        //+ propiedades


}
}

PimTeste/Models/UsuarioLogin.cs
using Microsoft.Extensions.Diagnostics.HealthChecks;
using PimTeste.Enums;
using System.ComponentModel.DataAnnotations;

namespace PimTeste.Models
{
    public class UsuarioLogin
    {
        public int Id { get; set; }
        [Required(ErrorMessage = " Digite o seu email")]
        public string? Email { get ; set; }
 
        [Required(ErrorMessage = " Digite sua senha ")]
        public string? senha { get; set; }
        public PerfilEnum Perfil { get; set; }
        //quando o usuário foi cadastrado e modificado;
        public DateTime DataCadastro { get; set; }
        public DateTime? AlteracaoUsuario { get; set; }


        // + prioridades 

    }
}

PimTeste/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace PimTeste.Controllers
{
    public class FuncionarioController : Controller
    {
        public IActionResult CadastrarFuncionario()
        {
            return View("CadastrarFuncionario");
        
        
        }
    }
}

PimTeste/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PimTeste.Models;
using System.Diagnostics;

namespace PimTeste.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Principal()
        {
            return View();
        }

       

       

    }
}

PimTeste/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using PimTeste.Context;
using PimTeste.Models;


namespace PimTeste.Controllers
{
    public class LoginController : Controller
    {
        private readonly AppDbContext _context;

        public LoginController(AppDbContext context) 
        {
         _context = context;
        
        }



        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EntrarTeste(UsuarioLogin usuarioLogin)
        {
            try 
            {
             var usuario = _context.UsuariosLogin.FirstOrDefault(u => u.Email == usuarioLogin.Email && u.senha == usuarioLogin.senha);
               
                if (usuario != null)
                {
                    // Usuário encontrado, redirecione para a página principal
                    return RedirectToAction("Principal", "Home");
                }
                else
                {
                    TempData["MensagemErro"] = "Ops, Usuário e/ou senha incorretos. Por favor, tente novamente.";
                    return View("Index");
                }

            } catch (Exception ex) 
            {
                TempData["MensagemErro"] = $"Ops, ocorreu um erro. Detalhe do erro: {ex.Message}";
                return RedirectToAction("Index");
            }


        }



    }
}

PimTeste/Views/Funcionario/CadastrarFuncionario.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/teste.css">
    <title>Home</title>
</head>
<body>

    <aside class="menu-lateral">
        <header class="header-menu">

            <div class="profile">
                <i class="fa-solid fa-user"></i>
            </div>

            <ul class="naveg">
                <li>
                    <a href="calcular-ferias.html"><i class="fa-solid fa-calculator"></i> Calcular férias</a>
                </li>
                <li>
                    <a href="apontamento-de-horas.html"><i class="fa-solid fa-clock"></i> Apontamento de horas</a>
                </li>
                <li>
                    <a href="relacao-de-ferias.html"><i class="fa-solid fa-umbrella-beach"></i> Relação de férias</a>
                </li>
                <li>
                    <a href="cadastrar-funcionario.html"><i class="fa-solid fa-right-from-bracket"></i> Cadastrar funcionário</a>
                </li>
                <li>
                    <a href="#"><i class="fa-solid fa-right-from-bracket"></i> Sair</a>
                </li>
            </ul>

        </header>
    </aside>

    <main class="dados-content">

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title">Cadastrar funcionário</h1>
                </div>
                <div class="col-md-6 fields">
                    <label for="">Nome:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-6 fields">
                    <label for="">CPF:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-4 fields">
                    <label for="">Departamento:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-4 fields">
                    <label for="">Salário:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-4 fields">
                    <label for="">Email:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-4 fields">
                    <label for="">Nascimento:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-4 fields">
                    <label for="">PIS:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-4 fields">
                    <label for="">RG:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-4 fields">
                    <label for="">Nome da mãe:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-4 fields">
                    <label for="">Nome do pai:</label>
                    <input class="form-control" type="text">
                </div>
                <div class="col-md-12 fields">
                    <button type="button" class="btn btn-success float-right">Enviar</button>
                </div>
            </div>
        </div>

    </main>




</body>
</html>

PimTeste/Views/Home/Principal.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/teste.css">
    <title>Home</title>
</head>

    <body>

    <aside class="menu-lateral">
        <header class="header-menu">

            <div class="profile">
                <i class="fa-solid fa-user"></i>
            </div>

            <nav class="nav-menu">
                <button>
                    <i class="fa-solid fa-calculator"></i>
                    <span>Cálcular férias</span>
                </button>

                <button>
                    <i class="fa-solid fa-clock"></i>
                    <span>Apontamento de horas</span>
                </button>

                <button>
                    <i class="fa-solid fa-umbrella-beach"></i>
                    <span>Relação de férias</span>
                </button>


                <form action ="@Url.Action("CadastrarFuncionario", "Funcionario")">
                    <button>
                            <i class="fa-solid fa-plus"></i>
                            <span>Cadastrar funcionário</span>
                    </button>

                </form>
             
                <div class="log-out">
                    <button>
                        <i class="fa-solid fa-right-from-bracket"></i>
                        <span>Sair</span>
                    </button>
                </div>
            </nav>

        </header>
    </aside>

    <main class="dados-content">



        <h1 class="tech">Desenvoltech</h1>


    </main>

</body>
</html>

PimTeste/Views/Login/Index.cshtml
@model PimTeste.Models.UsuarioLogin



<html>
<head>
   
    <title>Desenvoltech</title>
</head>

<body>
    <link rel="stylesheet" href="~/css/site.css">
    

    <main class="conteudo-principal">
        <div class="titulo">
            <h1 class="tech">Desenvoltech</h1>

        </div>
        <div class="forms-img">
            <form action="@Url.Action("EntrarTeste", "Login")" method="post" class="formulario">

                <fieldset class="form-content">
                    <legend>Faça o login com sua conta</legend>
                    <label for="email" class="label">E-mail</label>
                    <input type="email" asp-for="Email" name="Email" id="email" required placeholder="Digite seu email" class="campo-entrada">
                    @Html.ValidationMessageFor(x => x.Email)

                    <label for="senha" class="label">Senha</label>
                    <input type="password" asp-for="senha" name="senha" id="senha" required placeholder="Digite sua senha" class="campo-entrada">
                    @Html.ValidationMessageFor(x => x.senha)

                    <div class="btns-form">
                        <div class="radio">
                            <input type="radio" id="radio">
                            <label for="radio">Lembrar a senha</label>
                        </div>

                        <a href="#">Esqueceu sua senha?</a>
                    </div>

                    <button asp-controller="Login" asp-action="EntrarTeste" method="post" class="btn-form">Entrar</button>

                </fieldset>
            </form>
            <div class="logo">
                <img src="~/css/login.png" alt="">
            </div>
        </div>

    </main>

</body>
</html>